### ISSUE TITLE
Final Project

### ISSUE THREAD

**Issue by hieudayne** [hoangtin69/ProjectOOSD#3]

**Comment by hoangtin298** [comment]
- Final Report:
https://github.com/hoangtin69/ProjectOOSD/blob/master/Group9-RestaurantReservation-DesignPattern.pdf
https://github.com/hoangtin69/ProjectOOSD/blob/master/Group9-RestaurantReservation-Project.pdf
- C# code to demo:
https://github.com/hoangtin69/ProjectOOSD/tree/master/Group9-RestaurantReservation-Project/Group9-RestaurantReservation-Project
